server:
  port: 8085
  
spring:
  application:
    name: zuulserver

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    provision-service:
      path: /m2/**
      serviceId: provision-service
      strip-prefix: true
      #url: http://localhost:8082/
    cont-service:
      path: /m1/**
      serviceId:  cont-service
      strip-prefix: true
      #url: http://localhost:8081/
    cert-service:
      path: /m3/**
      serviceId:  cert-service
      strip-prefix: true
      #url: http://localhost:8080/
    zuulserver:
      path: /gateway/**
      serviceId:  zuulserver
      strip-prefix: true        

eureka:
  instance:
    hostname: eureka.adifv2.svc
    port: 8761
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  
endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false
